version: '3.6'
services:
  postgres:
    image: postgres:11.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: rkaadmin
      POSTGRES_PASSWORD: rka-2020
      POSTGRES_DB: rka
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
  graphql-engine:
    image: hasura/graphql-engine:v1.2.0-beta.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://rkaadmin:rka-2020@postgres:5432/rka
      # HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: royalkidsart
volumes:
  db_data:

